### ISSUE TITLE
Cannot start the project 

### ISSUE THREAD

**Issue by alonsogchparra** [Christianq010/netflix_landing-page#2]
Hi @Christianq010  how are you!? I was trying to (and still want xD) run the project, but the error that I got is this 
```
 netflix_landing-page git:(master) ✗ yarn start
yarn run v1.12.3
warning ../../../../../package.json: No license field
$ node scripts/start.js
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module '/Users/parra/Documents/workspace/react-course-projects/test_Stuff/netflix_landing-page/scripts/start.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:826:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm using 
node: v11.3.0
npm: 6.4.1
yarn: v1.12.3

I did these steps to make it work but without results:

- Delete yarn.lock, package-lock.json and node_modules
- Tried with `npm install` and `yarn install`
- Once I used `npm install` showed some vunerabilities after that I did `npm audit fix` and after that `npm audit fix --force` with those command the vunerabilities were gone. but it's still showing the same error.

I don't know if I still missing something or if the project I have to run it in a different branch. 

I liked the demo and I just want to practice to get better knowledge about landing page.

If you can tell me what else I can do to run the project will be very helpful.

Thanks for the attention and help.

**Comment by noth8** [comment]
The problem is in .gitignore file. The author of this repo added scripts dir to ignore and then upload changes. So you can't start/build/test project. This is another reason why not ejecting from create-react-app.

To fix this :

Create a new project with create-react-app.
Move src from this repo to the newly created project.
Run yarn add react-icons@^2.2.7 node-sass styled-components
Now you can launch project yarn start

**Comment by alonsogchparra** [comment]
@noth8 You're right, doing that fixed the trouble that I got trying to run the project. Thanks for the help! I left the project behind to practice react. But I will catch up again lol. This was very helpful
